package com.github.soulsearching.domain.navigation

/**
 * Routes names for navigation.
 */
enum class RoutesNames {
    MAIN_PAGE_SCREEN,
    SELECTED_PLAYLIST_SCREEN,
    SELECTED_ALBUM_SCREEN,
    SELECTED_ARTIST_SCREEN,
    MODIFY_PLAYLIST_SCREEN,
    MODIFY_ALBUM_SCREEN,
    MODIFY_ARTIST_SCREEN,
    MODIFY_MUSIC_SCREEN,
    MORE_PLAYLISTS_SCREEN,
    MORE_ALBUMS_SCREEN,
    MORE_ARTISTS_SCREEN,
    SETTINGS_SCREEN,
    SETTINGS_PERSONALISATION_SCREEN,
    SETTINGS_MANAGE_MUSICS_SCREEN,
    SETTINGS_USED_FOLDERS_SCREEN,
    SETTINGS_ADD_MUSICS_SCREEN,
    SETTINGS_COLOR_THEME_SCREEN,
    SETTINGS_ABOUT_SCREEN,
    SETTINGS_DEVELOPERS_SCREEN
}